name: nCryptCLI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Tests
    container: golang:1.14-alpine3
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: make test
